### ISSUE TITLE
Font Mastering

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fuggles#3]
**Diacritics**
- [x] Composite glyphs need to be made out of components using anchors
- [x] Comb.case are missing
- [x] Misaligned diacritics
- [x] Caron.alt needs to be included as a comb mark
- [x] Caron.alt glyphs need to be adjusted 

**Glyphs**
- [x] Add extreme points are missing

**OT Features**
- [x] Inspect everything is working well, e.g. all the ligatures and stylistic sets present in the font are included.
- [ ] Test them using the proof docs included in the documentation folder. Remember to name the PDF using the version number of the font.

**Comment by crystaltype** [comment]
> **Diacritics**
> 
> * [x]  Composite glyphs need to be made out of components using anchors
> * [x]  Comb.case are missing
> * [x]  Misaligned diacritics
> * [x]  Caron.alt needs to be included as a comb mark
> * [ ]  Caron.alt glyphs need to be adjusted
> 
> **Glyphs**
> 
> * [x]  Add extreme points are missing
> 
> **OT Features**
> 
> * [ ]  Inspect everything is working well, e.g. all the ligatures and stylistic sets present in the font are included.
> * [ ]  Test them using the proof docs included in the documentation folder. Remember to name the PDF using the version number of the font.

**Comment by vv-monsalve** [comment]
Hi @crystaltype,

I've pulled the latest files at commit cfc22d671c87dab7031f0a75a7ef475d28f52eca but received an Error when trying to produce the font:
`fontmake.errors.FontmakeError: In 'FugglesPro.glyphs' -> 'master_ufo/FugglesPro-Regular.designspace': Generating fonts from Designspace failed: /Users/vv_monsalve/Documents/03_GOOGLE/GF_Fonts/TypeSetIt/fuggles/sources/master_ufo/FugglesPro-Regular.ufo/features.fea:2:2428: The following glyph names are referenced but are missing from the glyph set: A.cap`

Please rename all the stylistic sets in the font so that they can be created automatically and therefore could be easily updated. Do this for all the projects as you are going through them.

CI action was already pushed.

Thanks
